#!/bin/bash
# Requires an installation of maven 2.x and Java 1.6 or higher
# Installs https://github.com/cltl/vua-resources.git if it isn't there already.
thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $thisdir
socketdir="$( cd ${thisdir} && cd .. && pwd)"
cd ${thisdir}
set -e

echo "#1. Check/install the vua-resources" >&2
cd "$socketdir"
if
  [ -d "vua-resources" ]
then
  cd vua-resources
  git pull
  cd ..
else
  git clone https://github.com/cltl/vua-resources.git
fi

echo "#2. compiling the library from source code and dependencies" >&2
cd ${thisdir}
mvn clean
mvn install

echo "#3. moving binary to lib folder" >&2
mkdir -p "$thisdir/lib"
jarfile=`find $thisdir/target -name "EventCoreference-v*-jar-with-dependencies.jar" -print`
if
  [ "$jarfile" == "" ]
then
  echo "could not generate the jar file. Sorry ..."
  exit 1
fi
mv $jarfile $thisdir/lib

#echo "#4. cleaning up"
#cd "$thisdir"
#rm -R target
#rm -R src
#rm EventCoreference.iml
#rm EventCoreference.iws
#rm EventCoreference.ipr
