#!/bin/bash
modname=EventCoreference
#
# Find the path to this module
#
if
  [ -z ${MODROOT+x} ]
then
  # Find out path ourselves
  thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
else
  thisdir=$MODROOT/$modname
fi
thisscript=${thisdir}/run
cd $thisdir
#
# Find the language
#
if
  [ -z "${NAFLANG+x}" ]
then
  naffile=`mktemp -t naf.XXXXXX`
  cat >$naffile
  NAFLANG=`cat $naffile | python ${thisdir}/langdetect.py` 
  export NAFLANG
  cat $naffile | $thisscript
  result=$?
  rm $naffile
  exit $result
fi
script="scripts/event-coreference-${NAFLANG}.sh"
cat | $script
